"""Closed enumerations stated explicitly by the frozen v6.1 contract."""

from __future__ import annotations

from enum import Enum


class ProbabilityScope(str, Enum):
    FINITE_OBSERVED_DATASET_SUBSAMPLING = (
        "FINITE_OBSERVED_DATASET_SUBSAMPLING"
    )
    WITHIN_REALIZED_LIBRARY_MODEL_CONDITIONAL = (
        "WITHIN_REALIZED_LIBRARY_MODEL_CONDITIONAL"
    )
    NEW_LIBRARY_ROBUST_MODEL_CONDITIONAL = (
        "NEW_LIBRARY_ROBUST_MODEL_CONDITIONAL"
    )
    SYNTHETIC_KNOWN_CHANNEL = "SYNTHETIC_KNOWN_CHANNEL"


class SplitRelation(str, Enum):
    INDEPENDENT_LIBRARIES = "INDEPENDENT_LIBRARIES"
    CONDITIONALLY_INDEPENDENT_UNITS_GIVEN_NUISANCE = (
        "CONDITIONALLY_INDEPENDENT_UNITS_GIVEN_NUISANCE"
    )
    RANDOM_PARTITION_OF_FINITE_OBSERVED_DATASET = (
        "RANDOM_PARTITION_OF_FINITE_OBSERVED_DATASET"
    )
    SHARED_BATCH_DEPENDENT = "SHARED_BATCH_DEPENDENT"
    UNKNOWN = "UNKNOWN"


class UnconditionalDerivation(str, Enum):
    TOWER_UNIFORM_ALMOST_SURE = "TOWER_UNIFORM_ALMOST_SURE"
    ABSTAIN_OUTSIDE_VALIDITY_EVENT = "ABSTAIN_OUTSIDE_VALIDITY_EVENT"
    GOOD_EVENT_UNION_BOUND = "GOOD_EVENT_UNION_BOUND"
    NOT_AVAILABLE = "NOT_AVAILABLE"


class CoverageBoundMethod(str, Enum):
    EXACT_ENUMERATION = "EXACT_ENUMERATION"
    VERIFIED_INTERVAL = "VERIFIED_INTERVAL"
    CERTIFIED_TRUNCATION = "CERTIFIED_TRUNCATION"
    MONTE_CARLO_ONLY = "MONTE_CARLO_ONLY"


class LockStage(str, Enum):
    A = "A"
    B = "B"
    C = "C"
    D = "D"


class TruthVisibility(str, Enum):
    HASH_ONLY = "HASH_ONLY"


class ExtendedValueTag(str, Enum):
    FINITE = "FINITE"
    POS_INF = "POS_INF"
    NA = "NA"


class RorcReason(str, Enum):
    REGISTERED_MODEL_CLASS_REJECTED = "REGISTERED_MODEL_CLASS_REJECTED"
    OUT_OF_SCOPE_STATE_DICTIONARY = "OUT_OF_SCOPE_STATE_DICTIONARY"
    RIVAL_SUPPORT_INCOMPLETE = "RIVAL_SUPPORT_INCOMPLETE"
    ABSTAIN_INDETERMINATE = "ABSTAIN_INDETERMINATE"


class PlannerFailureState(str, Enum):
    NO_CERTIFICATE_FOUND_BY_REGISTERED_PLANNER = (
        "NO_CERTIFICATE_FOUND_BY_REGISTERED_PLANNER"
    )
    NO_CERTIFICATE_WITHIN_AVAILABLE_CONTROL_LIBRARY = (
        "NO_CERTIFICATE_WITHIN_AVAILABLE_CONTROL_LIBRARY"
    )
    NO_FEASIBLE_FIXED_HORIZON_TEST_WITHIN_REGISTERED_DESIGN_CLASS = (
        "NO_FEASIBLE_FIXED_HORIZON_TEST_WITHIN_REGISTERED_DESIGN_CLASS"
    )
    PLANNER_UNRESOLVED = "PLANNER_UNRESOLVED"


class ExposureStatus(str, Enum):
    HISTORICALLY_SEMANTICALLY_EXPOSED_RETROSPECTIVE = (
        "HISTORICALLY_SEMANTICALLY_EXPOSED_RETROSPECTIVE"
    )
